version: "3.8"

services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - "./data:/data"
      - "./clickhouse-db:/var/lib/clickhouse"
    networks:
      - default

  pgsql:
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/poc
    ports:
      - "5432:5432"
    volumes:
      - "./data:/data"
      - "./postgres-db:/var/lib/postgresql/data"
    networks:
      - default

  manticore:
    image: manticoresearch/manticore:latest
    restart: always
    ports:
      - "9306:9306"
      - "9308:9308"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - MCL=1
    volumes:
      - ./manticore:/var/lib/manticore
    networks:
      - default

networks:
  default:
    external: true
    name: dbpoc-network
